добавляет разметку главной страницы
htmlacademy-htmlcss/1822045-gllacy-32 pull request #2
Opened 2021-09-30 10:02 UTC by SvetlanaKrapivina

2021-09-30 13:12 UTC, Dima-Dim requested changes

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +        <ul class="navigation-list navigation-user">
Начиная отсюда уже не главная навигация и эти элементы лучше не включать в тег nav.

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
Скорее всего здесь не сама форма, а лишь ссылка на неё. И эта ссылка относится к конретному слайду.

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +            <form class="get-present-form" action="https://echo.htmlacademy.ru/" method="POST">
Тоже просто ссылка на форму. И далее в похожих случаях тоже.

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +            <p class="advantage-1">Все наше мороженое изготавливается на собственном производстве, с использованием современного оборудования и проверенных временем технологий.</p>
Нам тут точно нужен тег p?

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +            <span class="form-label form-label-icon">
Для чего нам сейчас тут span?

2021-09-30 13:12 UTC, Dima-Dim commented on index.html
> +            <span class="form-label form-label-icon">
И тут для чего span?

2021-09-30 13:39 UTC, SvetlanaKrapivina commented on index.html
> +        <ul class="navigation-list navigation-user">
можно просто обернуть в <div class="user-navigation"....? или как отдельную секцию сделать?

2021-09-30 13:57 UTC, SvetlanaKrapivina commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
то есть имеется ввиду, что нажимая на кнопку "заказать" покупатель перекидывается на страничку с карточкой этого товара и более подробной информацией?

я тут решила, что при нажатии на "заказать", это товар сразу же добавляется в корзину и покупатель может дальше выбирать товары, не уходя с этой страницы

2021-09-30 14:16 UTC, SvetlanaKrapivina commented on index.html
> +            <p class="advantage-1">Все наше мороженое изготавливается на собственном производстве, с использованием современного оборудования и проверенных временем технологий.</p>
убрать <p> и поместить текст просто в <li>?

2021-09-30 14:44 UTC, Dima-Dim commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
Даже если сразу добавляется в корзину это не отравка формы на сервер.

2021-09-30 14:44 UTC, Dima-Dim commented on index.html
> +            <p class="advantage-1">Все наше мороженое изготавливается на собственном производстве, с использованием современного оборудования и проверенных временем технологий.</p>
Ага.

2021-09-30 21:58 UTC, SvetlanaKrapivina commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
хорошо, тут видимо нужно обернуть кнопку ЗАКАЗАТЬ в тег а? 
но мне тогда не очень понятно - почему в примере барбершопа кнопка КУПИТЬ обернута в тег а, а в статье академии про ссылки и кнопки написано, что "Кнопка — это функциональный элемент. Она отвечает за выполнение определённой функции: добавить в корзину, купить, отправить, проголосовать и т. д.
Для кнопок используют тег <button>."

2021-10-01 06:33 UTC, Dima-Dim commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
И кнопка, и ссылка — это интерактивные элементы, а интерактивный элемент не может быть в интерактивном элементе.
Нужно убрать обёртку, а виде форму и сменить тип кнопки на button.
"в примере барбершопа кнопка КУПИТЬ обернута в тег а" - где именно ты такое видишь?

2021-10-01 09:15 UTC, SvetlanaKrapivina commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
https://up.htmlacademy.ru/profession/frontender/12/htmlcss/demos/5943#29

176 строка

2021-10-01 09:51 UTC, Dima-Dim commented on index.html
> +        <form class="order-form" action="https://echo.htmlacademy.ru/" method="POST">
Да, вот теперь твоя формулировка верна и не вызывает вопросов :)

2021-10-01 18:09 UTC, Dima-Dim approved these changes

2021-10-01 18:09 UTC, merged