Графика и стилизация для всех страниц
htmlacademy-htmlcss/1822045-gllacy-32 pull request #4
Opened 2021-10-09 23:47 UTC by SvetlanaKrapivina

2021-10-10 07:57 UTC, Dima-Dim requested changes
Что-то стало слишком много html файлов, у нас же только 2 страницы в проекте.

Насколько я знаю, на лайве рассказывали вот про эти изображения images/catalog_items/item_1.png и тот вариант который ты для них выбрала не самый оптимальный.

images/icons/Cross.svg, images/icons/Покой.png и т.п. https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-03

2021-10-10 07:57 UTC, Dima-Dim commented on images/mail_bg.svg
> +<svg width="570" height="220" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path fill="url(#a)" d="M0 0h570v220H0z"/><defs><pattern id="a" patternContentU
Внутри этого файла не svg.

2021-10-10 07:57 UTC, Dima-Dim commented on styles/styles.css
> +width: 12px;
Тут проблема с форматированием.

2021-10-10 07:57 UTC, Dima-Dim commented on styles/styles.css
> +    background-image: url(../images/presents/item_1.png);
url(../images/presents/item_1.png) -> url("../images/presents/item_1.png")
и в других подобных местах так же.

2021-10-10 09:14 UTC, SvetlanaKrapivina commented
> Что-то стало слишком много html файлов, у нас же только 2 страницы в проекте.
> 
> Насколько я знаю, на лайве рассказывали вот про эти изображения images/catalog_items/item_1.png и тот вариант который ты для них выбрала не самый оптимальный.
> 
> images/icons/Cross.svg, images/icons/Покой.png и т.п. https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-03

лишние html файлы уберу, они пустые по ошибке попали. Товары из каталога нужно переименовать да? если я их назову например icecream_1, icecream_2 и тд? или все мороженки назвать по вкусам?

2021-10-11 16:39 UTC, Dima-Dim commented
> Насколько я знаю, на лайве рассказывали вот про эти изображения images/catalog_items/item_1.png и тот вариант который ты для них выбрала не самый оптимальный.

Нашёл этот момент на лайве за тебя https://youtu.be/8TDhBP0nNNY?t=1960

2021-10-12 07:01 UTC, Dima-Dim commented on styles/styles.css
> +    clip-path: circle(84px at 50% 50%);
Почему не border-radius? Почему изображения не заменила на jpg?

2021-10-14 11:40 UTC, merged